### ISSUE TITLE
Gallery items should be a collection

### ISSUE THREAD

**Issue by sawyerh** [siteleaf/siteleaf.com#11]
Just realized that all Gallery posts are in the `items` metadata field on the Gallery page 😱  It makes more sense for these to be separate documents in a `Gallery` collection. Currently this is a poor example to be showing other people.

![image](https://cloud.githubusercontent.com/assets/371943/18170468/74b9e60c-702c-11e6-8f62-eb10036a7ada.png)

**Comment by justinjaywang** [comment]
close via 25b329f1c74545837161ee438726a5c6baf57e6a
