### ISSUE TITLE
Favicon update?

### ISSUE THREAD

**Issue by justinjaywang** [siteleaf/siteleaf.com#12]
The favicon is looking a little blobby to me. At the very least, it could use an update on the leaf shape across the marketing site, learn site, and the Siteleaf app.

Thoughts, though, on something like this?

![siteleaf-favicon-1](https://cloud.githubusercontent.com/assets/2434384/18840424/8acd9786-83dc-11e6-8bed-406fed42c0af.png)
![siteleaf-favicon-2](https://cloud.githubusercontent.com/assets/2434384/18840423/8abfdaba-83dc-11e6-922e-cfd96684d992.png)

**Comment by sskylar** [comment]
I'm all for making it look less blobby when rendered at a low resolution like this, but not sure about the `s`.

**Comment by sawyerh** [comment]
![image](https://cloud.githubusercontent.com/assets/371943/18841424/b060da78-83df-11e6-8c28-ae540b7d09ca.png)
