### ISSUE TITLE
When inserting images add {{site.url}}{{site.basepath}}

### ISSUE THREAD

**Issue by dtsn** [siteleaf/siteleaf.com#17]
When I insert an image into my post only the relative link is added which works great across my multiple environments. However, on my feed (using jekyll-feed) none of my images so because all the paths are relative instead of absolute. Would it be possible to add {{site.url}}{{site.basepath}} (or similar) if they are in the config?

**Comment by sskylar** [comment]
@dtsn This repo is not intended for support questions. But since you asked, you should be able to do something like:

```
{{ foo | replace: "/uploads/", "http://foo.com/uploads/" }}
```

If you think this should be done automatically, you might want to raise a request in the `jekyll-feed` repo.

Hope that helps!

**Comment by dtsn** [comment]
👍  thanks, i'll raise an issue in `jekyll-feed`.
