### ISSUE TITLE
Archive v1 help site

### ISSUE THREAD

**Issue by sskylar** [siteleaf/siteleaf.com#4]
What should we do about archiving the v1 help site? 

It's going to get replaced by the new marketing site...

http://www.siteleaf.com/help/

**Comment by sawyerh** [comment]
Do we plan on archiving the entire V1 site? It's one benefit of static sites 😎

**Comment by sskylar** [comment]
I doubt we want to keep the old marketing page up, but maybe we just hide everything but help? and publish it to v1.siteleaf.com?

This top banner could mention its out of date and to visit learn.siteleaf.com for v2 ![](http://drp.mk/i/FhhRPCkZjm.png)

**Comment by sskylar** [comment]
Done http://v1.siteleaf.com
